/**
 * tools/build-vendor.mjs — builds vendor/codemirror.esm.js.
 *
 * The app ships with NO build step and NO install: the bundle below is committed,
 * exactly like the other vendored libraries (marked, DOMPurify). This script is
 * only needed when bumping CodeMirror. It needs the devDependencies.
 *
 *   npm install
 *   node tools/build-vendor.mjs
 *
 * Only the pieces this editor uses are included — no autocompletion, no linting,
 * no folding, no emmet. That is worth ~15 KB gzipped, but more importantly it
 * keeps the vendored surface small enough to audit.
 */
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Re-exported as a namespace so the app can do:
//   import { CM } from '../vendor/codemirror.esm.js';
const entry = `
export * as state from '@codemirror/state';
export * as view from '@codemirror/view';
export * as commands from '@codemirror/commands';
export * as language from '@codemirror/language';
export * as search from '@codemirror/search';
export * as markdown from '@codemirror/lang-markdown';
export * as highlight from '@lezer/highlight';
`;

const outfile = path.join(ROOT, 'vendor/codemirror.esm.js');

await build({
  stdin: { contents: entry, resolveDir: ROOT, sourcefile: 'codemirror-entry.mjs', loader: 'js' },
  bundle: true,
  format: 'esm',
  minify: true,
  legalComments: 'none',
  target: ['es2020'],
  outfile,
  logLevel: 'error',
  banner: {
    js: '/* codemirror.esm.js — generated by tools/build-vendor.mjs; do not edit by hand. */',
  },
});

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
const { execSync } = await import('node:child_process');
const raw = readFileSync(outfile).length;
const gz = execSync(`gzip -c ${JSON.stringify(outfile)} | wc -c`).toString().trim();
console.log(`vendor/codemirror.esm.js  ${kb(raw)} raw  ${kb(Number(gz))} gzipped`);

// Anything pinned here must match package.json; print it so a bump is visible.
for (const p of ['@codemirror/view', '@codemirror/state', '@codemirror/search',
                 '@codemirror/lang-markdown', '@codemirror/commands', '@codemirror/language']) {
  const pkg = JSON.parse(readFileSync(path.join(ROOT, 'node_modules', p, 'package.json'), 'utf8'));
  console.log(`  ${p}@${pkg.version}`);
}
